global:
  parallel: yes # yes/no
  hetergeneous: yes # yes/no
  if_exists: append_rows # append_rows, append_cols, append_both, drop, truncate
  sample: no # no/#
  propagate_global: yes # yes/no
  lone_data: [csv,tsv,fwf,xls,xlsx,xlsm]
transforms:
  row_index: eel_id
  load_date: eel_date
  data_file_name: eel_data_file
  data_frame_name: eel_data_frame
  eel_yml_name: eel_yml_file
  data_file_hash: no
  eel_yml_hash: no
target:
  type: csv
  file_path: 'test_export.csv'
source:
  type: mssql
  server: localhost
  database: bimx
  table: "[dbo].[dbMarketKnobloch]"