[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "els"
version = "0.0.3"

[project.scripts]
els = "els.cli:main"

[tool.setuptools.packages.find]
exclude = ['temp','graveyard']