source:
  url: ../source/Data.csv
target:
  url: ../target/WorldBankPopulation.csv
transforms: 
- melt:
    id_vars:
    - Country Name
    - Country Code
    - Indicator Name
    - Indicator Code
    value_name: Population
    var_name: Year
- as_type: 
    Population: Int64
- add_columns: 
    Source File: _file_name_full
