source:
  url: ../source/Data.csv
target:
  table: WorldBankPopulation
transforms: 
- melt:
    melt_id_vars:
    - Country Name
    - Country Code
    - Indicator Name
    - Indicator Code
    melt_value_name: Population
    melt_var_name: Year
- as_type: 
    as_dtypes:
      Population: Int64
- add_columns: 
    Date Downloaded: 2024-07-16
    Source File: _file_name_full
    another one: _row_index