from typing import Any

from sqlalchemy import TextClause
from sqlalchemy.engine.base import Engine
from sqlalchemy.engine.url import URL

def _sqlite_file_exists(database: str) -> bool: ...
def _get_scalar_result(engine: Engine, sql: TextClause) -> Any: ...
def _set_url_database(url: URL, database: Any) -> URL: ...
def database_exists(url: URL | str) -> bool: ...
def create_database(
    url: URL | str, encoding: str = ..., template: str | None = ...
) -> None: ...
def drop_database(url: URL | str) -> None: ...
