name: onpush
on:
  push:
    branches:
      - main
jobs:
  version-bump:
    uses: ./.github/workflows/version-bump.yml
    with:
      contents: write
      id-token: write
      # - name: test
      #   uses: test.yml@main