name: onpush
on:
  push:
    branches:
      - main
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: bump
        uses: ../.github/workflows/version-bump.yml
      # - name: test
      #   uses: test.yml@main