name: onpush
permissions:
  contents: write
  id-token: write
on:
  push:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/test.yml
  version-bump:
    needs: test
    uses: ./.github/workflows/version-bump.yml
  publish:
    needs: version-bump
    uses: ./.github/workflows/python-publish.yml