name: Python tests
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        sys:
          - os: windows-2022
            shell: powershell
            tox-args: -f win
            sqlcmd-path: sqlcmd
          - os: ubuntu-22.04
            shell: bash
            tox-args: -f lin -- -k 'not TestMSSQL_ODBC17'
            sqlcmd-path: /opt/mssql-tools18/bin/sqlcmd
          - os: macos-13
            shell: bash
            tox-args: -f mac
            sqlcmd-path: sqlcmd
    runs-on: ${{ matrix.sys.os }}
    defaults:
      run:
        shell: ${{ matrix.sys.shell }}
    steps:
      - name: Install a SQL Server suite of tools
        if: ${{ !env.ACT }}
        uses: NathanDWalsh/mssqlsuite@main
        with:
          install: sqlengine, sqlclient
          show-log: true
      - name: Run sqlclient
        run: |
          ${{ matrix.sys.sqlcmd-path }} -C -S localhost -U sa -P dbatools.I0 -d master -Q "drop database if exists els;"
          ${{ matrix.sys.sqlcmd-path }} -C -S localhost -U sa -P dbatools.I0 -d master -Q "create database els;"
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.9
            3.10
            3.11
            3.12
            3.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Test with tox
        run: |
          python -m tox ${{ matrix.sys.tox-args }}
